name:               plc-llvm
version:            0.1.0.0
github:             "HachiSecurity/plc-llvm"
author:             "Michael B. Gale"
maintainer:         "michael.gale@tweag.io"

dependencies:
- base
- bytestring
- containers
- directory
- filepath
- flat
- llvm-hs
- llvm-hs-pure
- mtl
- optparse-applicative
- plutus-core
- prettyprinter
- transformers
- typed-process

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  plc-llvm:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -Wall
    dependencies:
    - plc-llvm
