name:               plc-llvm
version:            0.1.0.0
github:             "HachiSecurity/plc-llvm"
author:             "Michael B. Gale"
maintainer:         "michael.gale@tweag.io"

dependencies:
- base
- bytestring
- containers
- directory
- extra
- filepath
- flat
- llvm-hs
- llvm-hs-pure
- mtl
- optparse-applicative
- plc-utils
- plutus-core
- prettyprinter
- some
- template-haskell
- text
- transformers
- typed-process

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- KindSignatures
- OverloadedStrings
- StandaloneKindSignatures

ghc-options:
- -Werror=missing-fields
- -Werror=missing-methods

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  plc-llvm:
    main:           Main.hs
    source-dirs:    app
    ghc-options:
    - -Wall
    dependencies:
    - plc-llvm

tests:
  plc-llvm-test:
    main:           Spec.hs
    source-dirs:    test
    ghc-options:
    - -Wall
    dependencies:
    - plc-llvm
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hedgehog
    - tasty-ant-xml
    - hedgehog
