name: build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - "compiler/**"
      - "stack*.yaml"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.4"
          enable-stack: true
          stack-version: "latest"

      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsodium-dev libgmp-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 12

      - name: Cache .stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: ${{ runner.os }}-

      - name: Install dependencies
        run: |
          stack --no-terminal build --only-dependencies --test --fast --system-ghc

      - name: Build
        run: |
          stack --no-terminal build --test --fast --system-ghc --no-run-tests

      - name: Run tests
        run: |
          stack --no-terminal build --test --fast --system-ghc --test-arguments='--xml=plc-llvm.xml'

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: compiler/plc-llvm.xml
          check_name: 'tests'
          comment_title: 'Test results'
          fail_on: 'test failures'
