name: docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - '.github/workflows/docker.yml'
      - 'lts*.yaml'
      - 'stack*.yaml'
      - 'compiler/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Configure Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/hachisecurity/plc-llvm
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Authenticate to package registry
        uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish plc-llvm image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
